### PR TITLE
Fixing typos in README

### PR DESCRIPTION
**Pull request by animesh-bhadouria**
*Issue #, if available:*

*Description of changes:*
- Fixing typos in README

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shimomut** [comment]
These ”:” characters are what I inserted intentionally to indicate that there are other omitted/hidden elements here.

**Comment by animesh-bhadouria** [comment]
maybe we can add a comment instead, this might confuse customers.

**Comment by shimomut** [comment]
I will replace ":" with something like "... snip ..."

**Comment by shimomut** [comment]
Updated the branch. Closing this pull request.

**Pull request closed without merging**
