### PR TITLE
Logs export tool

### PR DESCRIPTION
**Pull request by shimomut**
*Description of changes:*

Adding a tool (Python script) to help customers bulk dump Panorama related logs easily.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by SuryaKari — COMMENTED** [review]
please include the required permissions for the credentials for this log tool to work

**Comment by SuryaKari** [comment]
let us also include the format of the output logs for anyone using this tool or anyone using the output of this log tool

**Comment by shimomut** [comment]
Added "Permission setting" and "Output structure" to address your feedback @SuryaKari

**Review by SuryaKari — APPROVED** [review]
Approved

**Pull request merged**
