### PR TITLE
MOT analysis sample

### PR DESCRIPTION
**Pull request by jk1333**
Submitting new MOT analysis sample to start from

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mrtj** [comment]
Thank you for giving credits to the yolox article. FYI, I've just sent my next article to TDS for publication. The article introduces a library that makes it easy to stream processed video from Panorama to KVS (or to an RTSP server hosted in the application container). I can provide now the [link to the library](https://github.com/Neosperience/backpack), the article should be online in a day or two.

**Comment by jk1333** [comment]
@mrtj Thanks for great utilities and shares :) If I know the repo I wouldn't waist my time to working with KVS haha, Thanks for your yolox article also that was very helped and I'll update by using your KVS lib for next release

**Comment by shimomut** [comment]
Starting review.

**Comment by shimomut** [comment]
@jk1333 thank you for your contribution.

About this step in README:

"4. (Optional) Refer to ./mot_analysis_app/packages/{accountid}-MOT_ANALYSIS_CODE-1.0/Dockerfile and install necessary packages(OpenCV, gstreamer, kvssink and pytorch) to simulator for testing sample before deploy. Graviton instance only."

I didn't get clear idea what I should do, 1) when I use Windows + WSL2 + Ubuntu environment, and 2) when I use ARM EC2 environment.

I tried to run the app firstly on my Windows + WSL2 + Ubuntu. And I got import errors for following libraries.

* "torch"
* "lap"
* "Cython"
* "cython_bbox"

After installing these libraries, I got following error:

```
2022-05-23 14:48:37 ERROR    Exception during processing loop.
Traceback (most recent call last):
  File "app.py", line 262, in main
    app.process_streams()
  File "app.py", line 129, in process_streams
    self.videowriter.write(streams[self.STREAM_ID].image)
AttributeError: 'Application' object has no attribute 'videowriter'
```

I imagine I didn't install necessary dependencies before running the app with Test Utility. Could you provide some more information on this?

Thank you!

**Comment by jk1333** [comment]
@[shimomut](https://github.com/shimomut) I added additional package installation script for simulator as well as readme update. Thanks for pointing out of ambiguity!

**Comment by shimomut** [comment]
Thank you for addressing feedback. Merged to mainline.

**Pull request merged**
